import Anthropic from 'https://esm.sh/@anthropic-ai/sdk@0.36.3';
import { createLangfuseClient, LangfuseClient } from '../_shared/langfuse.ts';
import { evalRootCauseHypothesis } from '../_shared/online-eval.ts';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, sentry-hook-signature',
};

const MODEL = 'claude-haiku-4-5-20251001';

// ── Sentry webhook payload types ──────────────────────────────────────────────

interface SentryFrame {
  filename?: string;
  abs_path?: string;
  function?: string;
  lineno?: number;
  context_line?: string;
}

interface SentryException {
  type?: string;
  value?: string;
  stacktrace?: { frames?: SentryFrame[] };
}

interface SentryEvent {
  event_id?: string;
  title?: string;
  culprit?: string;
  platform?: string;
  environment?: string;
  level?: string;
  exception?: { values?: SentryException[] };
  tags?: Array<{ key: string; value: string }>;
  user?: { id?: string; email?: string };
}

interface SentryWebhookPayload {
  action?: string;
  data?: {
    event?: SentryEvent;
    issue?: {
      id?: string;
      title?: string;
      status?: string;
      permalink?: string;
      userCount?: number;
      firstSeen?: string;
    };
  };
  installation?: { uuid?: string };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

async function verifySignature(req: Request, body: string): Promise<boolean> {
  const secret = Deno.env.get('SENTRY_WEBHOOK_SECRET');
  if (!secret) return true;

  const signature = req.headers.get('sentry-hook-signature') ?? '';
  if (!signature) return false;

  const encoder = new TextEncoder();
  const cryptoKey = await crypto.subtle.importKey(
    'raw', encoder.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']
  );
  const signatureBuffer = await crypto.subtle.sign('HMAC', cryptoKey, encoder.encode(body));
  const computedHex = Array.from(new Uint8Array(signatureBuffer))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');

  return computedHex === signature;
}

async function postToSlack(webhookUrl: string, text: string): Promise<void> {
  await fetch(webhookUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ text }),
  });
}

async function githubReadFile(token: string, repo: string, path: string, ref = 'main'): Promise<string | null> {
  const res = await fetch(`https://api.github.com/repos/${repo}/contents/${path}?ref=${ref}`, {
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github.v3+json' },
  });
  if (!res.ok) return null;
  const json = await res.json();
  if (json.encoding === 'base64' && json.content) return atob(json.content.replace(/\n/g, ''));
  return null;
}

async function githubSearchCode(token: string, repo: string, query: string): Promise<Array<{ path: string; url: string }>> {
  const q = encodeURIComponent(`${query} repo:${repo}`);
  const res = await fetch(`https://api.github.com/search/code?q=${q}&per_page=3`, {
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github.v3+json' },
  });
  if (!res.ok) return [];
  const json = await res.json();
  return (json.items ?? []).map((item: any) => ({ path: item.path, url: item.html_url }));
}

async function githubCreateDraftPR(
  token: string, repo: string, issueId: string, title: string, body: string, diff: string, targetFile: string
): Promise<{ url: string; number: number } | null> {
  const branchName = `fix/sentry-${issueId}`;

  const refRes = await fetch(`https://api.github.com/repos/${repo}/git/refs/heads/main`, {
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github.v3+json' },
  });
  if (!refRes.ok) return null;
  const baseSha = (await refRes.json()).object?.sha;
  if (!baseSha) return null;

  const branchRes = await fetch(`https://api.github.com/repos/${repo}/git/refs`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github.v3+json', 'Content-Type': 'application/json' },
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
  });
  if (!branchRes.ok) return null;

  const fixNotePath = `.sentry-fixes/sentry-${issueId}.md`;
  const fixNoteContent = `# AI-Suggested Fix for Sentry Issue\n\n## Issue\n${title}\n\n## Suggested Diff\n\`\`\`diff\n${diff}\n\`\`\`\n\n> Generated by FreedomFire Sentry Agent. Review carefully before applying.\n`;

  const commitRes = await fetch(`https://api.github.com/repos/${repo}/contents/${fixNotePath}`, {
    method: 'PUT',
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github.v3+json', 'Content-Type': 'application/json' },
    body: JSON.stringify({ message: `fix: AI-suggested fix for Sentry issue ${issueId}`, content: btoa(fixNoteContent), branch: branchName }),
  });
  if (!commitRes.ok) return null;

  const prRes = await fetch(`https://api.github.com/repos/${repo}/pulls`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github.v3+json', 'Content-Type': 'application/json' },
    body: JSON.stringify({ title: `[AI Draft] ${title}`, body, head: branchName, base: 'main', draft: true }),
  });
  if (!prRes.ok) return null;
  const prData = await prRes.json();
  return { url: prData.html_url, number: prData.number };
}

// ── Stage implementations ─────────────────────────────────────────────────────

async function stage1Enrich(
  anthropic: Anthropic,
  event: SentryEvent,
  issue: SentryWebhookPayload['data']['issue'],
  slackUrl: string,
  lf: LangfuseClient,
  traceId: string,
  spanId: string
): Promise<string> {
  const exceptionValues = event.exception?.values ?? [];
  const topException = exceptionValues[0];
  const frames = (topException?.stacktrace?.frames ?? []).slice(-5);
  const frameText = frames.map(f => `  ${f.filename ?? f.abs_path ?? '?'}:${f.lineno ?? '?'} in ${f.function ?? '?'}`).join('\n');

  const contextText = [
    `Title: ${issue?.title ?? event.title ?? 'Unknown error'}`,
    `Platform: ${event.platform ?? 'unknown'}`,
    `Environment: ${event.environment ?? 'unknown'}`,
    `Level: ${event.level ?? 'error'}`,
    topException?.type ? `Exception: ${topException.type}: ${topException.value ?? ''}` : '',
    frameText ? `Top frames:\n${frameText}` : '',
    `Affected users: ${issue?.userCount ?? 0}`,
    `First seen: ${issue?.firstSeen ?? 'unknown'}`,
    `Sentry URL: ${issue?.permalink ?? 'N/A'}`,
  ].filter(Boolean).join('\n');

  const userPrompt = `Summarize this crash in one sentence for a Slack alert. Be specific about what failed and the likely user impact. Keep it under 120 characters.\n\n${contextText}`;
  const genId = crypto.randomUUID();
  const genStart = new Date();

  const response = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 512,
    messages: [{ role: 'user', content: userPrompt }],
  });

  lf.generation({
    id: genId,
    traceId,
    parentSpanId: spanId,
    name: 'stage1-summarise',
    model: MODEL,
    input: [{ role: 'user', content: userPrompt }],
    output: response.content,
    startTime: genStart,
    endTime: new Date(),
    usage: { input: response.usage.input_tokens, output: response.usage.output_tokens },
  });

  const summary = (response.content[0] as Anthropic.TextBlock).text.trim();
  const firstSeen = issue?.firstSeen
    ? new Date(issue.firstSeen).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Kolkata' })
    : 'unknown';

  await postToSlack(slackUrl, [
    `🔴 *${issue?.title ?? event.title ?? 'Unknown error'}*`,
    `Environment: ${event.environment ?? 'unknown'}  |  Affected users: ${issue?.userCount ?? 0}  |  First seen: ${firstSeen} IST`,
    `> ${summary}`,
    `Sentry: ${issue?.permalink ?? 'N/A'}`,
  ].join('\n'));

  return summary;
}

async function stage2RootCause(
  anthropic: Anthropic,
  event: SentryEvent,
  issue: SentryWebhookPayload['data']['issue'],
  slackUrl: string,
  githubToken: string,
  githubRepo: string,
  lf: LangfuseClient,
  traceId: string,
  spanId: string
): Promise<{ hypothesis: string; files: string[] }> {
  const exceptionValues = event.exception?.values ?? [];
  const topException = exceptionValues[0];
  const frames = (topException?.stacktrace?.frames ?? []).slice(-8);
  const frameText = frames.map(f => `${f.filename ?? f.abs_path ?? '?'}:${f.lineno ?? '?'} in ${f.function ?? '?'}`).join('\n');

  const readFileTool: Anthropic.Tool = {
    name: 'read_file',
    description: 'Read the contents of a source file from the GitHub repository',
    input_schema: {
      type: 'object' as const,
      properties: {
        path: { type: 'string', description: 'File path relative to repo root' },
        ref:  { type: 'string', description: 'Git ref (branch/commit/tag). Defaults to main.' },
      },
      required: ['path'],
    },
  };

  const searchCodeTool: Anthropic.Tool = {
    name: 'search_code',
    description: 'Search the repository for code matching a query. Returns top 3 matching files.',
    input_schema: {
      type: 'object' as const,
      properties: { query: { type: 'string' } },
      required: ['query'],
    },
  };

  const system = `You are a senior engineer performing root cause analysis on a production crash in the FreedomFire React Native / Expo app (Supabase backend, Deno Edge Functions).

Your job:
1. Use read_file and search_code tools to examine the relevant source code
2. Identify the most likely root cause
3. Output your findings as a JSON object with keys: hypothesis (string, ≤200 chars), files (array of file paths you examined)

Be precise. Reference specific functions, lines, or modules.`;

  const userMessage = `Analyze this crash and find the root cause:\n\nTitle: ${issue?.title ?? event.title}\nException: ${topException?.type ?? ''}: ${topException?.value ?? ''}\n\nStack frames:\n${frameText}\n\nUse the tools to read relevant source files, then output your analysis.`;

  const messages: Anthropic.MessageParam[] = [{ role: 'user', content: userMessage }];
  let hypothesis = 'Unable to determine root cause';
  const examinedFiles: string[] = [];
  let iterations = 0;
  const MAX_ITERATIONS = 6;

  while (iterations < MAX_ITERATIONS) {
    iterations++;
    const genId = crypto.randomUUID();
    const genStart = new Date();

    const response = await anthropic.messages.create({
      model: MODEL,
      max_tokens: 4096,
      system,
      messages,
      tools: [readFileTool, searchCodeTool],
    });

    lf.generation({
      id: genId,
      traceId,
      parentSpanId: spanId,
      name: `stage2-rca-iter-${iterations}`,
      model: MODEL,
      input: messages,
      output: response.content,
      startTime: genStart,
      endTime: new Date(),
      usage: { input: response.usage.input_tokens, output: response.usage.output_tokens },
    });

    messages.push({ role: 'assistant', content: response.content });

    if (response.stop_reason === 'end_turn') {
      const textBlock = response.content.find((b): b is Anthropic.TextBlock => b.type === 'text');
      if (textBlock) {
        try {
          const jsonMatch = textBlock.text.match(/\{[\s\S]*"hypothesis"[\s\S]*\}/);
          if (jsonMatch) {
            const parsed = JSON.parse(jsonMatch[0]);
            hypothesis = parsed.hypothesis ?? hypothesis;
            if (Array.isArray(parsed.files)) examinedFiles.push(...parsed.files);
          } else {
            hypothesis = textBlock.text.slice(0, 200);
          }
        } catch {
          hypothesis = textBlock.text.slice(0, 200);
        }
      }
      break;
    }

    if (response.stop_reason !== 'tool_use') break;

    const toolResults: Anthropic.ToolResultBlockParam[] = [];
    for (const block of response.content) {
      if (block.type !== 'tool_use') continue;
      let result = '';
      if (block.name === 'read_file') {
        const { path, ref } = block.input as { path: string; ref?: string };
        examinedFiles.push(path);
        const content = await githubReadFile(githubToken, githubRepo, path, ref);
        result = content ? content.slice(0, 3000) : `File not found: ${path}`;
      } else if (block.name === 'search_code') {
        const { query } = block.input as { query: string };
        const results = await githubSearchCode(githubToken, githubRepo, query);
        result = results.length > 0 ? results.map(r => `${r.path} — ${r.url}`).join('\n') : 'No results found';
      }
      toolResults.push({ type: 'tool_result', tool_use_id: block.id, content: result });
    }
    messages.push({ role: 'user', content: toolResults });
  }

  const uniqueFiles = [...new Set(examinedFiles)];
  const filesDisplay = uniqueFiles.map(f => `\`${f}\``).join(' · ') || '_No files examined_';

  await postToSlack(slackUrl, [
    `🔍 *Root Cause Analysis*`,
    `Issue: ${issue?.title ?? event.title}`,
    `Hypothesis: ${hypothesis}`,
    `Relevant files: ${filesDisplay}`,
  ].join('\n'));

  return { hypothesis, files: uniqueFiles };
}

async function stage3DraftPR(
  anthropic: Anthropic,
  event: SentryEvent,
  issue: SentryWebhookPayload['data']['issue'],
  rootCause: { hypothesis: string; files: string[] },
  slackUrl: string,
  githubToken: string,
  githubRepo: string,
  lf: LangfuseClient,
  traceId: string,
  spanId: string
): Promise<void> {
  const issueId = issue?.id ?? event.event_id ?? 'unknown';
  const issueTitle = issue?.title ?? event.title ?? 'Unknown error';
  const topException = event.exception?.values?.[0];

  const fixPrompt = `You are fixing a production crash in FreedomFire (React Native / Expo / Supabase).

Crash: ${issueTitle}
Exception: ${topException?.type ?? ''}: ${topException?.value ?? ''}
Root cause hypothesis: ${rootCause.hypothesis}
Files involved: ${rootCause.files.join(', ')}

Generate:
1. A short PR title (under 60 chars, no issue number)
2. A PR description explaining the fix (markdown, 3–5 bullet points)
3. A unified diff showing the suggested code change (use --- a/file +++ b/file format)
4. The primary file path this diff applies to

Respond as JSON: { "pr_title": "...", "pr_body": "...", "diff": "...", "target_file": "..." }`;

  const genId = crypto.randomUUID();
  const genStart = new Date();

  const response = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 4096,
    messages: [{ role: 'user', content: fixPrompt }],
  });

  lf.generation({
    id: genId,
    traceId,
    parentSpanId: spanId,
    name: 'stage3-draft-pr',
    model: MODEL,
    input: [{ role: 'user', content: fixPrompt }],
    output: response.content,
    startTime: genStart,
    endTime: new Date(),
    usage: { input: response.usage.input_tokens, output: response.usage.output_tokens },
  });

  const textBlock = response.content.find((b): b is Anthropic.TextBlock => b.type === 'text');
  let prTitle    = `Fix crash: ${issueTitle.slice(0, 50)}`;
  let prBody     = `Automated fix suggestion for Sentry issue.\n\n**Root cause**: ${rootCause.hypothesis}\n\n> ⚠️ AI-generated. Review carefully before merging.`;
  let diff       = '';
  let targetFile = rootCause.files[0] ?? 'unknown';

  if (textBlock) {
    try {
      const jsonMatch = textBlock.text.match(/\{[\s\S]*"pr_title"[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        prTitle    = parsed.pr_title ?? prTitle;
        prBody     = `${parsed.pr_body ?? ''}\n\n---\n⚠️ This is AI-generated. Review carefully before merging.\n\n**Sentry issue**: ${issue?.permalink ?? 'N/A'}`;
        diff       = parsed.diff ?? '';
        targetFile = parsed.target_file ?? targetFile;
      }
    } catch { /* use defaults */ }
  }

  const pr = await githubCreateDraftPR(githubToken, githubRepo, issueId, prTitle, prBody, diff, targetFile);

  if (pr) {
    await postToSlack(slackUrl, [`📋 *Draft PR Ready for Review*`, pr.url, `⚠️ This is AI-generated. Review carefully before merging.`].join('\n'));
  } else {
    await postToSlack(slackUrl, `⚠️ *Draft PR creation failed* for Sentry issue: ${issueTitle}\nManual investigation required.`);
  }
}

// ── Main handler ──────────────────────────────────────────────────────────────

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  const slackUrl     = Deno.env.get('SLACK_WEBHOOK_URL') ?? '';
  const githubToken  = Deno.env.get('GITHUB_TOKEN') ?? '';
  const githubRepo   = Deno.env.get('GITHUB_REPO') ?? '';
  const anthropicKey = Deno.env.get('ANTHROPIC_API_KEY') ?? '';

  if (!slackUrl || !anthropicKey) {
    return new Response(
      JSON.stringify({ error: 'Missing required environment variables (SLACK_WEBHOOK_URL, ANTHROPIC_API_KEY)' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }

  const bodyText = await req.text();
  if (!(await verifySignature(req, bodyText))) {
    return new Response(JSON.stringify({ error: 'Invalid webhook signature' }), {
      status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  let payload: SentryWebhookPayload;
  try {
    payload = JSON.parse(bodyText);
  } catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON payload' }), {
      status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  if (payload.action !== 'triggered' && payload.action !== 'created') {
    return new Response(JSON.stringify({ skipped: true, reason: `action=${payload.action}` }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  const event = payload.data?.event;
  const issue = payload.data?.issue;

  if (!event) {
    return new Response(JSON.stringify({ skipped: true, reason: 'no event in payload' }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  if (event.environment !== 'production') {
    return new Response(
      JSON.stringify({ skipped: true, reason: `environment=${event.environment}` }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }

  if (event.level && !['error', 'fatal', 'critical'].includes(event.level)) {
    return new Response(
      JSON.stringify({ skipped: true, reason: `level=${event.level}` }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }

  const anthropic = new Anthropic({ apiKey: anthropicKey });
  const traceId = crypto.randomUUID();
  const lf = createLangfuseClient();

  lf.trace({
    id: traceId,
    name: 'sentry-agent',
    tags: ['incident', event.environment ?? 'unknown'],
    metadata: {
      issueId: issue?.id,
      issueTitle: issue?.title ?? event.title,
      sentryUrl: issue?.permalink,
    },
  });

  const stagesCompleted: string[] = [];
  const errors: Array<{ stage: string; error: string }> = [];
  let rootCause: { hypothesis: string; files: string[] } | null = null;

  // Stage 1
  const span1Id = crypto.randomUUID();
  lf.span({ id: span1Id, traceId, name: 'stage-1-enrich', startTime: new Date() });
  try {
    await stage1Enrich(anthropic, event, issue, slackUrl, lf, traceId, span1Id);
    lf.span({ id: span1Id, traceId, name: 'stage-1-enrich', startTime: new Date(), endTime: new Date() });
    stagesCompleted.push('stage1');
  } catch (err: any) {
    errors.push({ stage: 'stage1', error: err.message ?? 'Unknown error' });
    lf.span({ id: span1Id, traceId, name: 'stage-1-enrich', startTime: new Date(), endTime: new Date(), level: 'ERROR', statusMessage: err.message });
    await postToSlack(slackUrl, `⚠️ *Sentry Agent — Stage 1 failed*\nIssue: ${issue?.title ?? 'Unknown'}\nError: ${err.message ?? 'Unknown'}`).catch(() => {});
  }

  // Stage 2
  if (githubToken && githubRepo) {
    const span2Id = crypto.randomUUID();
    lf.span({ id: span2Id, traceId, name: 'stage-2-root-cause', startTime: new Date() });
    try {
      rootCause = await stage2RootCause(anthropic, event, issue, slackUrl, githubToken, githubRepo, lf, traceId, span2Id);

      // Online eval — root cause quality
      const evalResult = evalRootCauseHypothesis(rootCause.hypothesis);
      lf.score({ traceId, name: 'root_cause_quality', value: evalResult.value, comment: JSON.stringify(evalResult.detail) });
      lf.span({ id: span2Id, traceId, name: 'stage-2-root-cause', startTime: new Date(), endTime: new Date() });
      stagesCompleted.push('stage2');
    } catch (err: any) {
      errors.push({ stage: 'stage2', error: err.message ?? 'Unknown error' });
      lf.span({ id: span2Id, traceId, name: 'stage-2-root-cause', startTime: new Date(), endTime: new Date(), level: 'ERROR', statusMessage: err.message });
      await postToSlack(slackUrl, `⚠️ *Sentry Agent — Stage 2 failed*\nIssue: ${issue?.title ?? 'Unknown'}\nError: ${err.message ?? 'Unknown'}`).catch(() => {});
    }

    // Stage 3
    if (rootCause) {
      const span3Id = crypto.randomUUID();
      lf.span({ id: span3Id, traceId, name: 'stage-3-draft-pr', startTime: new Date() });
      try {
        await stage3DraftPR(anthropic, event, issue, rootCause, slackUrl, githubToken, githubRepo, lf, traceId, span3Id);
        lf.span({ id: span3Id, traceId, name: 'stage-3-draft-pr', startTime: new Date(), endTime: new Date() });
        stagesCompleted.push('stage3');
      } catch (err: any) {
        errors.push({ stage: 'stage3', error: err.message ?? 'Unknown error' });
        lf.span({ id: span3Id, traceId, name: 'stage-3-draft-pr', startTime: new Date(), endTime: new Date(), level: 'ERROR', statusMessage: err.message });
        await postToSlack(slackUrl, `⚠️ *Sentry Agent — Stage 3 failed*\nIssue: ${issue?.title ?? 'Unknown'}\nError: ${err.message ?? 'Unknown'}`).catch(() => {});
      }
    }
  } else {
    errors.push({ stage: 'stage2+3', error: 'GITHUB_TOKEN or GITHUB_REPO not configured — skipping root cause and PR creation' });
  }

  await lf.flush();

  return new Response(
    JSON.stringify({ stagesCompleted, errors }),
    { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
  );
});
